# Generated by Django 4.0.3 on 2022-04-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_courses', models.CharField(max_length=255, verbose_name='Название языка или продукта')),
                ('dates_of_the_event', models.DateTimeField(verbose_name='Даты проведения')),
                ('mentor_courses', models.CharField(max_length=255, verbose_name='Преподаватель')),
                ('course_completion_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Процент освоения темы')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_time', models.DateTimeField(auto_created=True, verbose_name='Время выполнения')),
                ('date_exam', models.DateTimeField(auto_now_add=True, verbose_name='Дата экзамена')),
                ('recommendations', models.TextField(blank=True, null=True, verbose_name='Общие рекомендации')),
                ('solved_task', models.TextField(blank=True, null=True, verbose_name='Решенное задание')),
                ('result', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Результаты')),
            ],
            options={
                'verbose_name': 'Экзамен',
                'verbose_name_plural': 'Эказамены',
            },
        ),
        migrations.CreateModel(
            name='SubTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Подтема',
                'verbose_name_plural': 'Подтемы',
            },
        ),
    ]
