# Generated by Django 4.0.3 on 2022-04-04 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtheme',
            name='lesson_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_block_sub_theme', to='lessons.lessonblock', verbose_name='Блок занятий'),
        ),
        migrations.AddField(
            model_name='subtheme',
            name='list_of_homework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_homework', to='lessons.hometask', verbose_name='Список ДЗ'),
        ),
        migrations.AddField(
            model_name='subtheme',
            name='list_of_lessons',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_lesson', to='lessons.lesson', verbose_name='Список уроков'),
        ),
        migrations.AddField(
            model_name='exam',
            name='lesson_block',
            field=models.ManyToManyField(related_name='lesson_block_exam', to='lessons.lessonblock', verbose_name='Блокт занятий'),
        ),
        migrations.AddField(
            model_name='courses',
            name='sub_theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_theme_course', to='courses.subtheme', verbose_name='Подтемы'),
        ),
    ]
