# Generated by Django 4.0.3 on 2022-04-04 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='Номер')),
                ('name_block', models.CharField(max_length=255, verbose_name='Название')),
                ('goal_at_the_end', models.TextField(blank=True, null=True, verbose_name='цель по окончании')),
            ],
            options={
                'verbose_name': 'Блок занятия',
                'verbose_name_plural': 'Блок занятий',
            },
        ),
        migrations.CreateModel(
            name='NewTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='название')),
                ('material', models.TextField(blank=True, null=True, verbose_name='материал')),
                ('practical_exercises', models.TextField(blank=True, null=True, verbose_name='практические упражнения')),
            ],
        ),
        migrations.CreateModel(
            name='Reflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='текст')),
                ('feedback', models.CharField(blank=True, max_length=255, null=True, verbose_name='обратной связи')),
            ],
        ),
        migrations.CreateModel(
            name='TermsBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='название')),
            ],
        ),
        migrations.CreateModel(
            name='Updating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='содержит название')),
                ('practical_exercises', models.TextField(blank=True, null=True, verbose_name='практические упражнения')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivation', models.TextField(blank=True, null=True, verbose_name='Мотивация')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Комментарии')),
                ('date_lesson', models.DateField(auto_now=True, verbose_name='дата')),
                ('group', models.CharField(blank=True, max_length=255, null=True, verbose_name='группа')),
                ('lesson_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_block_lesson', to='lessons.lessonblock', verbose_name='Блок занятий')),
                ('new_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_new_topic', to='lessons.newtopic', verbose_name='Новая тема')),
                ('reflection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflection_lesson', to='lessons.reflection')),
                ('updating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_updating', to='lessons.updating')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
        migrations.CreateModel(
            name='HomeTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_lesson_task', models.DateTimeField(auto_now=True, verbose_name='Дата')),
                ('topic', models.CharField(blank=True, max_length=255, null=True, verbose_name='Темы')),
                ('task', models.TextField(blank=True, null=True, verbose_name='Задание')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_home_task', to='lessons.lesson')),
            ],
            options={
                'verbose_name': 'Домашнее задание',
                'verbose_name_plural': 'Домашнее задание',
            },
        ),
        migrations.CreateModel(
            name='Glossary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.TextField(blank=True, null=True, verbose_name='Термин')),
                ('definition', models.TextField(blank=True, null=True, verbose_name='Определение')),
                ('using', models.TextField(blank=True, null=True, verbose_name='Использование')),
                ('lesson_url', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_url_data', to='lessons.lesson')),
                ('sub_theme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sub_theme_glossary', to='courses.subtheme')),
                ('terms_block', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terms_blocks', to='lessons.termsblock', verbose_name='Блок терминов')),
            ],
        ),
    ]
